# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170410_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbauth',
            name='facebook_token',
            field=models.CharField(max_length=600, verbose_name='Facebook auth token'),
        ),
    ]
